help:		#Show Help
	@fgrep -h '#' $(MAKEFILE_LIST) | grep -v fgrep

mongodb:	#Install Mongodb
	@bash components/mongodb.sh

catalogue:	#Install Catalogue
	@bash components/catalogue.sh

cart:		#Install Cart
	@bash components/cart.sh

frontend: 	#Install Frontend
	@bash components/frontend.sh

mysql: 		#Install MySQL
	@bash components/mysql.sh

payment: 	#Install Payment
	@bash components/payment.sh

rabbitmq: 	#Install RabbitMQ
	@bash components/rabbitmq.sh

redis:		#Install Redis
	@bash components/redis.sh

shipping: 	#Install Shipping
	@bash components/shipping.sh

user: 		#Install user
	@bash components/user.sh